# Generated by Django 3.2.7 on 2021-09-03 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='site',
            field=models.URLField(),
        ),
    ]
